/*
 * Curated starter catalogue, reviewed 2026-10-05.
 * No live schedules, prices, ratings or opening status are implied.
 * Each real place records its reviewed address/area, point label and sources.
 * Catalogue evidence: docs/catalogue.md. Photo credits: docs/image-credits.md.
 * Coordinates were checked against published venue points on 2026-10-05.
 * coordinateSourceUrl records the map source independently of the place's
 * information page. Visit Astana coordinates are its embedded ymaps.Placemark
 * / coords values. Mosque and aquarium points are Yandex business coordinates.
 * The sphere uses the coordinates published by alem.ai itself.
 * Map points identify the venue or park, not an accessible entrance.
 * Only events are fictional demos; venueId identifies their real host point.
 */
const categories = {
  attraction: { label: 'Достопримечательности', color: '#087e8b' },
  event: { label: 'События · Примеры', color: '#a6478c' },
  park: { label: 'Парки', color: '#398052' },
  food: { label: 'Еда', color: '#b96c2c' },
  culture: { label: 'Культура', color: '#7564a8' },
  shopping: { label: 'Шопинг', color: '#4e74a6' }
};

const attractions = [
  {
    id: 'baiterek',
    googlePlaceId: 'ChIJ99yqDB6ERUIROR0Rh__gbE8',
    routeQuery: '4CHJ+86C Bäiterek, Астана 01000',
    name: 'Байтерек',
    aliases: ['Baiterek', 'Bayterek', 'Бәйтерек'],
    coordinates: [51.128314, 71.430519],
    coordinateSourceUrl: 'https://visitastana.kz/ru/map/',
    category: 'attraction',
    summary: 'Смотровая площадка с видом на бульвар и левый берег.',
    image: {
      "src": "assets/photos/baiterek.webp",
      "alt": "Золотой шар и ажурная конструкция монумента Байтерек.",
      "width": 800,
      "height": 533,
      "credit": "Фото: Quarot · кадрировано, WebP",
      "creditUrl": "https://commons.wikimedia.org/wiki/File:Baiterek_August.jpg",
      "license": "CC0 1.0",
      "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en"
    },
    description: 'Поднимитесь на смотровую площадку внутри золотого шара, чтобы увидеть бульвар Нуржол и застройку левого берега сверху. У подножия можно рассмотреть конструкцию монумента и снять его на фоне города.',
    icon: 'attraction',
    address: 'Бульвар Нуржол, 14',
    pointLabel: 'Здание монумента',
    verifiedAt: '2026-10-05',
    kind: 'place',
    area: 'Бульвар Нуржол',
    tags: ['Панорама', 'Архитектура', 'Фото'],
    sourceUrl: 'https://a-vm.kz/objects/bayterek/',
    sourceLabel: 'Оператор Байтерека · Astana Venue Management',
    demo: false
  },
  {
    id: 'khan-shatyr',
    googlePlaceId: 'ChIJx-EpM5uGRUIRvZyffLJAjE8',
    routeQuery: 'Хан Шатыр, Тұран данғылы 37, Астана 020000',
    name: 'Хан Шатыр',
    aliases: ['Khan Shatyr', 'Хан-Шатыр', 'Ханшатыр'],
    coordinates: [51.132599, 71.403817],
    coordinateSourceUrl: 'https://visitastana.kz/ru/map/',
    category: 'shopping',
    summary: 'Магазины, кинотеатр и фудкорт под шатром Нормана Фостера.',
    image: {
      "src": "assets/photos/khan-shatyr.webp",
      "alt": "Шатёр торгового центра Хан Шатыр.",
      "width": 800,
      "height": 533,
      "credit": "Фото: Quarot · уменьшено, WebP",
      "creditUrl": "https://commons.wikimedia.org/wiki/File:Khan_Shatyr.jpg",
      "license": "CC0 1.0",
      "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en"
    },
    description: 'Рассмотрите наклонный шатёр Нормана Фостера снаружи, а внутри найдите магазины, фудкорт и кинотеатр. Подойдёт для сочетания архитектурной прогулки с отдыхом под крышей.',
    icon: 'tent',
    address: 'Проспект Туран, 37',
    pointLabel: 'Здание торгового центра',
    verifiedAt: '2026-10-05',
    kind: 'place',
    area: 'Левый берег · проспект Туран',
    tags: ['Под крышей', 'Магазины', 'С семьёй'],
    sourceUrl: 'https://site.khanshatyr.com/ru',
    sourceLabel: 'Официальный сайт Хан Шатыр',
    demo: false
  },
  {
    id: 'nur-astana-mosque',
    googlePlaceId: 'ChIJzfILUyeERUIR_PY8wZBAHl4',
    routeQuery: '«Әбу Насыр Әл-Фараби» мешіті, Қабанбай батыр даңғылы 36, Астана 010000',
    name: 'Мечеть Абу Насыр аль-Фараби',
    aliases: ['Нур-Астана', 'Нур Астана', 'Nur-Astana Mosque', 'Abu Nasr Al-Farabi'],
    coordinates: [51.126654, 71.415796],
    coordinateSourceUrl: 'https://yandex.kz/maps/org/abu_nasyr_al_farabi_meshiti/1089167953/',
    category: 'attraction',
    summary: 'Золотой купол, четыре минарета и двор с фонтанами.',
    image: {
      "src": "assets/photos/nur-astana-mosque.webp",
      "alt": "Золотой купол и минареты мечети Абу Насыр аль-Фараби за осенними деревьями.",
      "width": 800,
      "height": 410,
      "credit": "Фото: Vyacheslav Bukharov · уменьшено, WebP",
      "creditUrl": "https://commons.wikimedia.org/wiki/File:Astana-2021-10_-_41.jpg",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
    },
    description: 'Рассмотрите золотой купол, четыре минарета и двор с двумя фонтанами. Мечеть, ранее называвшаяся «Нур-Астана», интересна сочетанием белых фасадов и исламского декора. Правила входа внутрь уточните у мечети.',
    icon: 'mosque',
    address: 'Проспект Кабанбай батыра, 36',
    pointLabel: 'Здание мечети',
    verifiedAt: '2026-10-05',
    kind: 'place',
    area: 'Проспект Кабанбай батыра',
    tags: ['Архитектура', 'История', 'Мечеть'],
    sourceUrl: 'https://ummet.kz/ru/o-mecheti.html',
    sourceLabel: 'Официальный сайт мечети',
    demo: false
  },
  {
    id: 'palace-of-peace-and-reconciliation',
    googlePlaceId: 'ChIJOV47j_eDRUIRcBT1GvqDTm0',
    routeQuery: 'Бейбітшілік және келісім сарайы, Тәуелсіздік даңғылы 57, Астана 010000',
    name: 'Дворец мира и согласия',
    aliases: ['Palace of Peace and Reconciliation', 'Пирамида'],
    coordinates: [51.123085, 71.463288],
    coordinateSourceUrl: 'https://visitastana.kz/ru/about-city/what-to-see/dvorets-mira-i-soglasiya/',
    category: 'attraction',
    summary: 'Стеклянная пирамида и парк для прогулки и фотографий.',
    image: {
      "src": "assets/photos/palace-of-peace-and-reconciliation.webp",
      "alt": "Пирамида Дворца мира и согласия с дорожками окружающего парка.",
      "width": 800,
      "height": 533,
      "credit": "Фото: Davide Mauro · уменьшено, WebP",
      "creditUrl": "https://commons.wikimedia.org/wiki/File:Presidential_Park_04.jpg",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
    },
    description: 'Стеклянная пирамида Нормана Фостера с геометрическими фасадами; её удобно рассматривать и фотографировать из окружающего парка. Внутри есть выставочные и концертные залы — доступ и программу уточните перед визитом.',
    icon: 'pyramid',
    address: 'Проспект Тауелсиздик, 57',
    pointLabel: 'Здание пирамиды',
    verifiedAt: '2026-10-05',
    kind: 'place',
    area: 'Проспект Тауелсиздик',
    tags: ['Архитектура', 'Выставки', 'Фото'],
    sourceUrl: 'https://visitastana.kz/ru/about-city/what-to-see/dvorets-mira-i-soglasiya/',
    sourceLabel: 'Visit Astana',
    demo: false
  },
  {
    id: 'expo-nur-alem',
    googlePlaceId: 'ChIJBZWlvhnGhiARn_G8Kfrrwc0',
    routeQuery: 'Alem.ai - Международный центр искусственного интеллекта, пр-т. Мангилик Ел. 55/1, Астана 010000',
    name: 'Нур Алем · alem.ai',
    aliases: ['EXPO Nur Alem', 'Нур-Алем', 'Экспо', 'Alem.ai', 'AI Alem', 'Музей сингулярности'],
    coordinates: [51.0892, 71.4161],
    coordinateSourceUrl: 'https://alem.ai/ru/',
    category: 'culture',
    summary: 'Сфера EXPO и интерактивный Музей сингулярности об ИИ.',
    image: {
      "src": "assets/photos/expo-nur-alem.webp",
      "alt": "Сфера Нур Алем на фоне грозового неба.",
      "width": 800,
      "height": 450,
      "credit": "Фото: Vadimure · уменьшено, WebP",
      "creditUrl": "https://commons.wikimedia.org/wiki/File:Storm_over_Astana_1.jpg",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
    },
    description: 'Сфера EXPO-2017 теперь вмещает центр искусственного интеллекта alem.ai. На первом этаже — Музей сингулярности с интерактивными и иммерсивными экспозициями об ИИ. Можно осмотреть сферу снаружи или запланировать посещение музея.',
    icon: 'sphere',
    address: 'Проспект Мангилик Ел, блок B1 · EXPO',
    pointLabel: 'Сферическое здание Нур Алем',
    verifiedAt: '2026-10-05',
    kind: 'place',
    area: 'Территория EXPO',
    tags: ['Архитектура', 'Музей', 'Технологии', 'Под крышей'],
    sourceUrl: 'https://alem.ai/ru/',
    sourceLabel: 'Официальный сайт alem.ai',
    demo: false
  },
  {
    id: 'central-park',
    googlePlaceId: 'ChIJ476EiMWGRUIRK0nC8VtaaTw',
    routeQuery: '5C4C+C2 Astanalyq Ortalyq Saiabaq, Астана 020000',
    name: 'Центральный парк',
    aliases: ['Central Park', 'Центральный городской парк'],
    coordinates: [51.152859, 71.41902],
    coordinateSourceUrl: 'https://visitastana.kz/ru/about-city/what-to-see/tsentralnyy-park/',
    category: 'park',
    summary: 'Аллеи, берег Есиля, велодорожки и детские площадки.',
    image: {
      "src": "assets/photos/central-park.webp",
      "alt": "Берег Есиля у восточной стороны Центрального парка.",
      "width": 800,
      "height": 600,
      "credit": "Фото: Vmenkov · уменьшено, WebP",
      "creditUrl": "https://commons.wikimedia.org/wiki/File:Astana-Ishim-River-Lake-7793.jpg",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0"
    },
    description: 'Пройдитесь по аллеям среди деревьев и выйдите к берегу Есиля. В парке есть велосипедные и беговые дорожки, детские площадки и зоны отдыха: можно выбрать спокойную прогулку или провести время с детьми.',
    icon: 'park',
    pointLabel: 'Прогулочная зона внутри парка',
    verifiedAt: '2026-10-05',
    kind: 'place',
    area: 'Берег Есиля · Центральный парк',
    tags: ['Прогулка', 'На воздухе', 'С семьёй'],
    sourceUrl: 'https://visitastana.kz/ru/about-city/what-to-see/tsentralnyy-park/',
    sourceLabel: 'Visit Astana',
    demo: false
  },
  {
    id: 'astana-opera',
    googlePlaceId: 'ChIJ1bEghpmGRUIR4m_Boh67xl0',
    routeQuery: 'Astana Operası, Дінмұхамед Қонаев көшесі 1, Астана 010000',
    name: 'Астана Опера',
    aliases: ['Astana Opera', 'Оперный театр'],
    coordinates: [51.135622, 71.410827],
    coordinateSourceUrl: 'https://visitastana.kz/ru/about-city/what-to-see/teatr-opery-i-baleta-astana-opera/',
    category: 'culture',
    summary: 'Опера, балет и концерты в театре с колоннадой.',
    image: {
      "src": "assets/photos/astana-opera.webp",
      "alt": "Главный фасад Астана Опера с колоннадой.",
      "width": 800,
      "height": 600,
      "credit": "Фото: Nikolamikovic82 · кадрировано, WebP",
      "creditUrl": "https://commons.wikimedia.org/wiki/File:The_State_Opera_and_Ballet_Theatre_%E2%80%9CAstana_Opera%E2%80%9D.jpg",
      "license": "CC0 1.0",
      "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en"
    },
    description: 'Осмотрите театр с колоннадой и казахскими мотивами в оформлении. Чтобы увидеть сцену и интерьеры, выберите оперу, балет или концерт в официальной афише; для прогулки без спектакля интересен сам фасад.',
    icon: 'theater',
    address: 'Улица Динмухамеда Кунаева, 1',
    pointLabel: 'Здание театра',
    programUrl: 'https://astanaopera.kz/afisha',
    programLabel: 'Афиша на сайте театра',
    verifiedAt: '2026-10-05',
    kind: 'place',
    area: 'Улица Динмухамеда Кунаева',
    tags: ['Театр', 'Балет', 'Архитектура'],
    sourceUrl: 'https://astanaopera.kz/contacts',
    sourceLabel: 'Официальный сайт театра',
    demo: false
  },
  {
    id: 'national-museum-of-kazakhstan',
    googlePlaceId: 'ChIJRUatDPSDRUIRoBpFGrFIC_8',
    routeQuery: 'Qazaqstan Respublikasynyñ Ūlttyq Mūrajaiy, Тәуелсіздік даңғылы 54, Астана 010000',
    name: 'Национальный музей Казахстана',
    aliases: ['National Museum of Kazakhstan', 'Национальный музей Республики Казахстан'],
    coordinates: [51.118105, 71.469506],
    coordinateSourceUrl: 'https://visitastana.kz/ru/map/',
    category: 'culture',
    summary: 'История Казахстана, археологические находки и работы художников.',
    image: {
      "src": "assets/photos/national-museum-of-kazakhstan.webp",
      "alt": "Главный зал Национального музея Казахстана с золотым орлом под потолком.",
      "width": 800,
      "height": 600,
      "credit": "Фото: Davide Mauro · кадрировано, WebP",
      "creditUrl": "https://commons.wikimedia.org/wiki/File:National_Museum_of_the_Republic_of_Kazakhstan_01.jpg",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
    },
    description: 'Рассмотрите археологические находки, познакомьтесь с историей Казахстана и работами художников в музейных залах. Подойдёт для вдумчивого знакомства со страной; состав экспозиций и временные выставки проверьте на сайте музея.',
    icon: 'culture',
    address: 'Проспект Тауелсиздик, 54',
    pointLabel: 'Здание музея',
    verifiedAt: '2026-10-05',
    kind: 'place',
    area: 'Проспект Тауелсиздик',
    tags: ['Музей', 'История', 'Под крышей'],
    sourceUrl: 'https://nmrk.kz/ru/',
    sourceLabel: 'Официальный сайт музея',
    demo: false
  },
  {
    id: 'mega-silk-way',
    googlePlaceId: 'ChIJ4av6Rq-FRUIRN4g63bqh90s',
    routeQuery: 'MEGA Silk Way COO, 010000, просп. Кабанбай Батыра 62, Астана 010000',
    name: 'MEGA Silk Way',
    aliases: ['Мега', 'Мега Силк Вей'],
    coordinates: [51.089234, 71.407349],
    coordinateSourceUrl: 'https://visitastana.kz/ru/about-city/what-to-see/mega-silk-way/',
    category: 'shopping',
    summary: 'Магазины, рестораны, кино и детские развлечения рядом с EXPO.',
    image: {
      "src": "assets/photos/mega-silk-way.webp",
      "alt": "Вход в торговый центр MEGA Silk Way.",
      "width": 800,
      "height": 450,
      "credit": "Фото: RG72 · уменьшено, WebP",
      "creditUrl": "https://commons.wikimedia.org/wiki/File:A%C4%89etcentro_SilkWay_(Astano)_01.jpg",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
    },
    description: 'Магазины, рестораны, кинотеатр и детские развлечения рядом с EXPO. Здесь можно поесть и отдохнуть под крышей до или после посещения сферы Нур Алем.',
    icon: 'shopping',
    address: 'Проспект Кабанбай батыра, 62',
    pointLabel: 'Здание торгового центра',
    verifiedAt: '2026-10-05',
    kind: 'place',
    area: 'Рядом с EXPO',
    tags: ['Магазины', 'Кино', 'С семьёй'],
    sourceUrl: 'https://visitastana.kz/ru/about-city/what-to-see/mega-silk-way/',
    sourceLabel: 'Visit Astana · MEGA Silk Way',
    demo: false
  },
  {
    id: 'line-brew',
    googlePlaceId: 'ChIJ9-_Ll9CGRUIRDVUKzd8Pu4Q',
    routeQuery: 'Line Brew Astana, Кенесары көшесі 20, Астана 010000',
    name: 'Line Brew · Кенесары',
    aliases: ['Line Brew', 'Лайн Брю', 'Лайн Брев', 'Ресторан Line Brew'],
    coordinates: [51.163658, 71.416047],
    coordinateSourceUrl: 'https://visitastana.kz/ru/about-city/where-to-eat/line-brew6199/',
    category: 'food',
    summary: 'Стейки и гриль в интерьере средневекового стиля.',
    description: 'Стейки и блюда на гриле в ресторане с интерьером в средневековом стиле. На карте выбран филиал на Кенесары, 20, на правом берегу; он подойдёт для ужина после прогулки по старой части города. Меню уточните на сайте ресторана.',
    icon: 'food',
    address: 'Улица Кенесары, 20',
    pointLabel: 'Филиал на Кенесары, 20',
    verifiedAt: '2026-10-05',
    kind: 'place',
    area: 'Улица Кенесары',
    tags: ['Ресторан', 'Европейская кухня', 'Стейки'],
    sourceUrl: 'https://line-group.kz/line_brew',
    sourceLabel: 'Официальный сайт Line Group',
    demo: false
  },
  {
    id: 'duman-entertainment-center',
    googlePlaceId: 'ChIJU1o1H-mDRUIRMEblwSZmPPs',
    routeQuery: 'Ailand, Коргалжинское ш. 2, Астана 020000',
    name: 'Океанариум Ailand',
    aliases: ['Duman Entertainment Center', 'Думан', 'Айленд'],
    coordinates: [51.147018, 71.415143],
    coordinateSourceUrl: 'https://yandex.kz/maps/org/mukhitaral/216784633350/',
    category: 'attraction',
    summary: 'Подводный тоннель, акулы, черепахи и другие морские обитатели.',
    image: {
      "src": "assets/photos/duman-entertainment-center.webp",
      "alt": "Акула и дайвер за стеклом океанариума Ailand.",
      "width": 800,
      "height": 600,
      "credit": "Фото: Мазур Владимир · уменьшено, WebP",
      "creditUrl": "https://commons.wikimedia.org/wiki/File:%D0%9E%D0%BA%D0%B5%D0%B0%D0%BD%D0%B0%D1%80%D0%B8%D1%83%D0%BC_%D0%90%D1%81%D1%82%D0%B0%D0%BD%D0%B0_2018_1.jpg",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
    },
    description: 'Пройдите по прозрачному подводному тоннелю и понаблюдайте за акулами, черепахами и другими морскими обитателями. Океанариум расположен в комплексе Ailand, ранее известном как «Думан», и подходит для семейного посещения под крышей.',
    icon: 'fish',
    address: 'Коргалжынское шоссе, 2 · комплекс Ailand',
    pointLabel: 'Океанариум внутри комплекса Ailand',
    routeDestinationLabel: 'Комплекс Ailand · океанариум внутри',
    verifiedAt: '2026-10-05',
    kind: 'place',
    area: 'Коргалжынское шоссе',
    tags: ['Океанариум', 'С семьёй', 'Под крышей'],
    sourceUrl: 'https://ailand.kz/ru/',
    sourceLabel: 'Официальный сайт Ailand',
    demo: false
  },
  {
    id: 'presidential-park',
    googlePlaceId: 'ChIJp3Vrbg-ERUIRnKidw-UPj5o',
    routeQuery: '4FF5+XVM Президенттік саябақ, Сарайшық көшесі, Астана 010000',
    name: 'Президентский парк',
    aliases: ['Presidential Park'],
    coordinates: [51.123894, 71.459161],
    coordinateSourceUrl: 'https://visitastana.kz/ru/about-city/what-to-see/prezidentskiy-park/',
    category: 'park',
    summary: 'Прогулочные дорожки и виды на Дворец мира и согласия.',
    image: {
      "src": "assets/photos/presidential-park.webp",
      "alt": "Зелёные дорожки и водоёмы Президентского парка с пирамидой вдали.",
      "width": 800,
      "height": 533,
      "credit": "Фото: Davide Mauro · уменьшено, WebP",
      "creditUrl": "https://commons.wikimedia.org/wiki/File:Presidential_Park_01.jpg",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
    },
    description: 'Прогуляйтесь по дорожкам и открытым зелёным пространствам вокруг Дворца мира и согласия. Отсюда можно рассмотреть пирамиду с разных сторон и совместить архитектурную фотопрогулку с отдыхом в парке.',
    icon: 'park',
    pointLabel: 'Прогулочная зона западнее пирамиды',
    verifiedAt: '2026-10-05',
    kind: 'place',
    area: 'Проспект Тауелсиздик · вокруг Дворца мира и согласия',
    tags: ['Прогулка', 'На воздухе', 'Фото'],
    sourceUrl: 'https://visitastana.kz/ru/about-city/what-to-see/prezidentskiy-park/',
    sourceLabel: 'Visit Astana',
    demo: false
  },
  {
    id: 'demo-chamber-evening',
    venueId: 'astana-opera',
    name: 'Вечер камерной музыки',
    aliases: ['Концерт', 'Музыка', 'Астана Опера'],
    coordinates: [51.135622, 71.410827],
    category: 'event',
    summary: 'Пример: камерный концерт в театре «Астана Опера».',
    description: 'Вымышленный пример события: камерный концерт в театре «Астана Опера». Карточка показывает, как будет выглядеть будущая афиша. Такой концерт не анонсирован; дата, программа и билеты не назначены.',
    kind: 'event',
    area: 'Астана Опера · пример площадки',
    tags: ['Концерт', 'Музыка', 'Демо'],
    eventLabel: 'Пример события · дата не назначена',
    demo: true
  },
  {
    id: 'demo-city-exhibition',
    venueId: 'national-museum-of-kazakhstan',
    name: 'Город в деталях',
    aliases: ['Выставка', 'Фотография', 'Национальный музей'],
    coordinates: [51.118105, 71.469506],
    category: 'event',
    summary: 'Пример: фотовыставка об архитектуре и повседневной жизни Астаны.',
    description: 'Вымышленная идея фотовыставки об архитектуре и повседневной жизни Астаны. Национальный музей выбран только как пример площадки для демонстрации карты. Реальная выставка с такой программой не заявлена.',
    kind: 'event',
    area: 'Национальный музей · пример площадки',
    tags: ['Выставка', 'Фотография', 'Демо'],
    eventLabel: 'Пример события · дата не назначена',
    demo: true
  },
  {
    id: 'demo-park-sketching',
    venueId: 'central-park',
    name: 'Прогулка со скетчбуком',
    aliases: ['Мастер-класс', 'Рисование', 'Центральный парк'],
    coordinates: [51.152859, 71.41902],
    category: 'event',
    summary: 'Пример: прогулка с зарисовками деревьев и реки в парке.',
    description: 'Вымышленный пример творческой встречи: прогулка и зарисовки деревьев, реки и городских деталей в Центральном парке. Это демонстрация будущей афиши, без организатора, даты или регистрации.',
    kind: 'event',
    area: 'Центральный парк · пример площадки',
    tags: ['Мастер-класс', 'На воздухе', 'Демо'],
    eventLabel: 'Пример события · дата не назначена',
    demo: true
  }
];

for (const event of attractions.filter(place => place.kind === 'event')) {
  const venue = attractions.find(place => place.id === event.venueId && place.kind === 'place');
  if (!venue) throw new Error(`Unknown venue for ${event.id}`);
  event.coordinates = [...venue.coordinates];
}
